# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/hasing/Workspace/soc_project/vivado/lab4_1.srcs/sources_1/bd/lab4_soc/ip/lab4_soc_processing_system7_0_1/lab4_soc_processing_system7_0_1.xci
# IP: The module: 'lab4_soc_processing_system7_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/hasing/Workspace/soc_project/vivado/lab4_1.srcs/sources_1/bd/lab4_soc/ip/lab4_soc_processing_system7_0_1/lab4_soc_processing_system7_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab4_soc_processing_system7_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/hasing/Workspace/soc_project/vivado/lab4_1.srcs/sources_1/bd/lab4_soc/ip/lab4_soc_processing_system7_0_1/lab4_soc_processing_system7_0_1.xci
# IP: The module: 'lab4_soc_processing_system7_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/hasing/Workspace/soc_project/vivado/lab4_1.srcs/sources_1/bd/lab4_soc/ip/lab4_soc_processing_system7_0_1/lab4_soc_processing_system7_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab4_soc_processing_system7_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
