# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/Lab3_block/Lab3_block.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab3_block || ORIG_REF_NAME==Lab3_block} -quiet] -quiet

# IP: bd/Lab3_block/ip/Lab3_block_processing_system7_0_0/Lab3_block_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab3_block_processing_system7_0_0 || ORIG_REF_NAME==Lab3_block_processing_system7_0_0} -quiet] -quiet

# IP: bd/Lab3_block/ip/Lab3_block_ps7_0_axi_periph_0/Lab3_block_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab3_block_ps7_0_axi_periph_0 || ORIG_REF_NAME==Lab3_block_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/Lab3_block/ip/Lab3_block_rst_ps7_0_100M_0/Lab3_block_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab3_block_rst_ps7_0_100M_0 || ORIG_REF_NAME==Lab3_block_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/Lab3_block/ip/Lab3_block_MYMULTIPLIER_1_0/Lab3_block_MYMULTIPLIER_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab3_block_MYMULTIPLIER_1_0 || ORIG_REF_NAME==Lab3_block_MYMULTIPLIER_1_0} -quiet] -quiet

# IP: bd/Lab3_block/ip/Lab3_block_auto_pc_0/Lab3_block_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab3_block_auto_pc_0 || ORIG_REF_NAME==Lab3_block_auto_pc_0} -quiet] -quiet

# XDC: bd/Lab3_block/Lab3_block_ooc.xdc
