# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/hasing/Workspace/soc_project/vivado/lab4_1.srcs/sources_1/bd/lab4_soc/ip/lab4_soc_ZedboardOLED_0_0/lab4_soc_ZedboardOLED_0_0.xci
# IP: The module: 'lab4_soc_ZedboardOLED_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/hasing/Workspace/soc_project/vivado/lab4_1.srcs/sources_1/bd/lab4_soc/ip/lab4_soc_ZedboardOLED_0_0/src/charLib/charLib.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==charLib || ORIG_REF_NAME==charLib} -quiet] -quiet

# XDC: /home/hasing/Workspace/soc_project/vivado/lab4_1.srcs/sources_1/bd/lab4_soc/ip/lab4_soc_ZedboardOLED_0_0/src/charLib/charLib_ooc.xdc

# IP: /home/hasing/Workspace/soc_project/vivado/lab4_1.srcs/sources_1/bd/lab4_soc/ip/lab4_soc_ZedboardOLED_0_0/lab4_soc_ZedboardOLED_0_0.xci
# IP: The module: 'lab4_soc_ZedboardOLED_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/hasing/Workspace/soc_project/vivado/lab4_1.srcs/sources_1/bd/lab4_soc/ip/lab4_soc_ZedboardOLED_0_0/src/charLib/charLib.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==charLib || ORIG_REF_NAME==charLib} -quiet] -quiet

# XDC: /home/hasing/Workspace/soc_project/vivado/lab4_1.srcs/sources_1/bd/lab4_soc/ip/lab4_soc_ZedboardOLED_0_0/src/charLib/charLib_ooc.xdc
