# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/Lab2_SoC/Lab2_SoC.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab2_SoC || ORIG_REF_NAME==Lab2_SoC} -quiet] -quiet

# IP: bd/Lab2_SoC/ip/Lab2_SoC_processing_system7_0_0/Lab2_SoC_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab2_SoC_processing_system7_0_0 || ORIG_REF_NAME==Lab2_SoC_processing_system7_0_0} -quiet] -quiet

# IP: bd/Lab2_SoC/ip/Lab2_SoC_axi_gpio_0_0/Lab2_SoC_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab2_SoC_axi_gpio_0_0 || ORIG_REF_NAME==Lab2_SoC_axi_gpio_0_0} -quiet] -quiet

# IP: bd/Lab2_SoC/ip/Lab2_SoC_ps7_0_axi_periph_0/Lab2_SoC_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab2_SoC_ps7_0_axi_periph_0 || ORIG_REF_NAME==Lab2_SoC_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/Lab2_SoC/ip/Lab2_SoC_rst_ps7_0_100M_0/Lab2_SoC_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab2_SoC_rst_ps7_0_100M_0 || ORIG_REF_NAME==Lab2_SoC_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/Lab2_SoC/ip/Lab2_SoC_auto_pc_0/Lab2_SoC_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab2_SoC_auto_pc_0 || ORIG_REF_NAME==Lab2_SoC_auto_pc_0} -quiet] -quiet

# XDC: bd/Lab2_SoC/Lab2_SoC_ooc.xdc
