# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/hasing/Workspace/soc_project/ip_repo/zedboard_audio/constraints/zed_audio.xdc

# XDC: /home/hasing/Workspace/soc_project/vivado/ip_repo/SoC_Design/IPs/OLED/oled_constraints.xdc

# Block Designs: bd/lab4_soc/lab4_soc.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab4_soc || ORIG_REF_NAME==lab4_soc} -quiet] -quiet

# IP: bd/lab4_soc/ip/lab4_soc_processing_system7_0_1/lab4_soc_processing_system7_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab4_soc_processing_system7_0_1 || ORIG_REF_NAME==lab4_soc_processing_system7_0_1} -quiet] -quiet

# IP: bd/lab4_soc/ip/lab4_soc_zed_audio_0_0/lab4_soc_zed_audio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab4_soc_zed_audio_0_0 || ORIG_REF_NAME==lab4_soc_zed_audio_0_0} -quiet] -quiet

# IP: bd/lab4_soc/ip/lab4_soc_xlconstant_0_0/lab4_soc_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab4_soc_xlconstant_0_0 || ORIG_REF_NAME==lab4_soc_xlconstant_0_0} -quiet] -quiet

# IP: bd/lab4_soc/ip/lab4_soc_FILTER_IIR_0_0/lab4_soc_FILTER_IIR_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab4_soc_FILTER_IIR_0_0 || ORIG_REF_NAME==lab4_soc_FILTER_IIR_0_0} -quiet] -quiet

# IP: bd/lab4_soc/ip/lab4_soc_ps7_0_axi_periph_0/lab4_soc_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab4_soc_ps7_0_axi_periph_0 || ORIG_REF_NAME==lab4_soc_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/lab4_soc/ip/lab4_soc_rst_ps7_0_100M_0/lab4_soc_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab4_soc_rst_ps7_0_100M_0 || ORIG_REF_NAME==lab4_soc_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/lab4_soc/ip/lab4_soc_Volume_Pregain_0_0/lab4_soc_Volume_Pregain_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab4_soc_Volume_Pregain_0_0 || ORIG_REF_NAME==lab4_soc_Volume_Pregain_0_0} -quiet] -quiet

# IP: bd/lab4_soc/ip/lab4_soc_xbar_0/lab4_soc_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab4_soc_xbar_0 || ORIG_REF_NAME==lab4_soc_xbar_0} -quiet] -quiet

# IP: bd/lab4_soc/ip/lab4_soc_xlconcat_0_0/lab4_soc_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab4_soc_xlconcat_0_0 || ORIG_REF_NAME==lab4_soc_xlconcat_0_0} -quiet] -quiet

# IP: bd/lab4_soc/ip/lab4_soc_mixer_0_0/lab4_soc_mixer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab4_soc_mixer_0_0 || ORIG_REF_NAME==lab4_soc_mixer_0_0} -quiet] -quiet

# IP: bd/lab4_soc/ip/lab4_soc_FILTER_IIR_1_1/lab4_soc_FILTER_IIR_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab4_soc_FILTER_IIR_1_1 || ORIG_REF_NAME==lab4_soc_FILTER_IIR_1_1} -quiet] -quiet

# IP: bd/lab4_soc/ip/lab4_soc_Volume_Pregain_1_0/lab4_soc_Volume_Pregain_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab4_soc_Volume_Pregain_1_0 || ORIG_REF_NAME==lab4_soc_Volume_Pregain_1_0} -quiet] -quiet

# IP: bd/lab4_soc/ip/lab4_soc_axitoaudio_0_1/lab4_soc_axitoaudio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab4_soc_axitoaudio_0_1 || ORIG_REF_NAME==lab4_soc_axitoaudio_0_1} -quiet] -quiet

# IP: bd/lab4_soc/ip/lab4_soc_ZedboardOLED_0_0/lab4_soc_ZedboardOLED_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab4_soc_ZedboardOLED_0_0 || ORIG_REF_NAME==lab4_soc_ZedboardOLED_0_0} -quiet] -quiet

# IP: bd/lab4_soc/ip/lab4_soc_axi_gpio_0_0/lab4_soc_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab4_soc_axi_gpio_0_0 || ORIG_REF_NAME==lab4_soc_axi_gpio_0_0} -quiet] -quiet

# IP: bd/lab4_soc/ip/lab4_soc_auto_pc_0/lab4_soc_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab4_soc_auto_pc_0 || ORIG_REF_NAME==lab4_soc_auto_pc_0} -quiet] -quiet

# XDC: bd/lab4_soc/lab4_soc_ooc.xdc
