# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/hasing/workspace/lab3/vivado/lab3.srcs/sources_1/bd/Lab3_block/ip/Lab3_block_rst_ps7_0_100M_0/Lab3_block_rst_ps7_0_100M_0.xci
# IP: The module: 'Lab3_block_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/hasing/workspace/lab3/vivado/lab3.srcs/sources_1/bd/Lab3_block/ip/Lab3_block_rst_ps7_0_100M_0/Lab3_block_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab3_block_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/hasing/workspace/lab3/vivado/lab3.srcs/sources_1/bd/Lab3_block/ip/Lab3_block_rst_ps7_0_100M_0/Lab3_block_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab3_block_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/hasing/workspace/lab3/vivado/lab3.srcs/sources_1/bd/Lab3_block/ip/Lab3_block_rst_ps7_0_100M_0/Lab3_block_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab3_block_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/hasing/workspace/lab3/vivado/lab3.srcs/sources_1/bd/Lab3_block/ip/Lab3_block_rst_ps7_0_100M_0/Lab3_block_rst_ps7_0_100M_0.xci
# IP: The module: 'Lab3_block_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/hasing/workspace/lab3/vivado/lab3.srcs/sources_1/bd/Lab3_block/ip/Lab3_block_rst_ps7_0_100M_0/Lab3_block_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab3_block_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/hasing/workspace/lab3/vivado/lab3.srcs/sources_1/bd/Lab3_block/ip/Lab3_block_rst_ps7_0_100M_0/Lab3_block_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab3_block_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/hasing/workspace/lab3/vivado/lab3.srcs/sources_1/bd/Lab3_block/ip/Lab3_block_rst_ps7_0_100M_0/Lab3_block_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab3_block_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
